export const status = [
  { id: 1, name: "On Testing" },
  { id: 2, name: "On Development" },
  { id: 3, name: "On Production" },
  { id: 4, name: "On Deployment" },
  { id: 5, name: "On Review" },
  { id: 6, name: "On Hold" },
  { id: 7, name: "On Progress" },
  { id: 8, name: "On Queue" },
];

export const data = [
  {
    id: 1,
    tasks: "Kym",
    status: null,
    notes: "Nulla nisl.",
    due_date: "8/6/2024",
    entry_date: "2/8/2025",
  },
  {
    id: 2,
    tasks: "Dominique",
    status: null,
    notes:
      "Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    due_date: "2/8/2025",
    entry_date: "4/27/2024",
  },
  {
    id: 3,
    tasks: "Jackelyn",
    status: null,
    notes: "Maecenas ut massa quis augue luctus tincidunt.",
    due_date: "4/15/2024",
    entry_date: "4/30/2024",
  },
  {
    id: 4,
    tasks: "Timmy",
    status: null,
    notes:
      "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.",
    due_date: "7/6/2024",
    entry_date: "7/18/2024",
  },
  {
    id: 5,
    tasks: "Bert",
    status: null,
    notes:
      "Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    due_date: "5/12/2024",
    entry_date: "7/6/2024",
  },
  {
    id: 6,
    tasks: "Craig",
    status: null,
    notes: "Curabitur at ipsum ac tellus semper interdum.",
    due_date: "7/16/2024",
    entry_date: "9/2/2024",
  },
  {
    id: 7,
    tasks: "Rogers",
    status: null,
    notes:
      "Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.",
    due_date: "2/20/2025",
    entry_date: "11/21/2024",
  },
  {
    id: 8,
    tasks: "Gawain",
    status: null,
    notes: "Nulla nisl. Nunc nisl.",
    due_date: "8/14/2024",
    entry_date: "4/10/2024",
  },
  {
    id: 9,
    tasks: "Ignacio",
    status: null,
    notes: "Morbi ut odio.",
    due_date: "10/6/2024",
    entry_date: "5/26/2024",
  },
  {
    id: 10,
    tasks: "Pearce",
    status: null,
    notes: "Proin at turpis a pede posuere nonummy.",
    due_date: "8/10/2024",
    entry_date: "8/17/2024",
  },
  {
    id: 11,
    tasks: "Oliy",
    status: null,
    notes: "Vestibulum ac est lacinia nisi venenatis tristique.",
    due_date: "7/26/2024",
    entry_date: "1/6/2025",
  },
  {
    id: 12,
    tasks: "Melita",
    status: null,
    notes: "Cras non velit nec nisi vulputate nonummy.",
    due_date: "11/22/2024",
    entry_date: "5/9/2024",
  },
  {
    id: 13,
    tasks: "Nelson",
    status: null,
    notes: "Nullam molestie nibh in lectus.",
    due_date: "1/21/2025",
    entry_date: "7/12/2024",
  },
  {
    id: 14,
    tasks: "Grantley",
    status: null,
    notes: "Sed sagittis.",
    due_date: "1/10/2025",
    entry_date: "12/30/2024",
  },
  {
    id: 15,
    tasks: "Maressa",
    status: null,
    notes: "Proin interdum mauris non ligula pellentesque ultrices.",
    due_date: "5/12/2024",
    entry_date: "4/25/2024",
  },
  {
    id: 16,
    tasks: "Tiertza",
    status: null,
    notes: "Ut tellus. Nulla ut erat id mauris vulputate elementum.",
    due_date: "12/15/2024",
    entry_date: "8/8/2024",
  },
  {
    id: 17,
    tasks: "Atlanta",
    status: null,
    notes: "Etiam pretium iaculis justo.",
    due_date: "11/20/2024",
    entry_date: "10/2/2024",
  },
  {
    id: 18,
    tasks: "Val",
    status: null,
    notes: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    due_date: "7/14/2024",
    entry_date: "8/12/2024",
  },
  {
    id: 19,
    tasks: "Gwenni",
    status: null,
    notes: "Nulla mollis molestie lorem.",
    due_date: "10/19/2024",
    entry_date: "8/20/2024",
  },
  {
    id: 20,
    tasks: "Francois",
    status: null,
    notes: "Maecenas pulvinar lobortis est.",
    due_date: "5/27/2024",
    entry_date: "1/16/2025",
  },
  {
    id: 21,
    tasks: "Annadiane",
    status: null,
    notes:
      "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.",
    due_date: "8/22/2024",
    entry_date: "2/3/2025",
  },
  {
    id: 22,
    tasks: "Leon",
    status: null,
    notes:
      "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.",
    due_date: "8/27/2024",
    entry_date: "11/1/2024",
  },
  {
    id: 23,
    tasks: "Billye",
    status: null,
    notes:
      "Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    due_date: "6/9/2024",
    entry_date: "8/7/2024",
  },
  {
    id: 24,
    tasks: "Zachary",
    status: null,
    notes: "Etiam pretium iaculis justo. In hac habitasse platea dictumst.",
    due_date: "11/27/2024",
    entry_date: "3/30/2024",
  },
  {
    id: 25,
    tasks: "Pepillo",
    status: null,
    notes: "Vivamus in felis eu sapien cursus vestibulum.",
    due_date: "1/17/2025",
    entry_date: "8/1/2024",
  },
  {
    id: 26,
    tasks: "Marlow",
    status: null,
    notes: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    due_date: "11/21/2024",
    entry_date: "2/1/2025",
  },
  {
    id: 27,
    tasks: "Romy",
    status: null,
    notes:
      "In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.",
    due_date: "11/15/2024",
    entry_date: "4/21/2024",
  },
  {
    id: 28,
    tasks: "Angy",
    status: null,
    notes:
      "Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.",
    due_date: "5/13/2024",
    entry_date: "10/8/2024",
  },
  {
    id: 29,
    tasks: "Carl",
    status: null,
    notes:
      "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.",
    due_date: "10/28/2024",
    entry_date: "2/22/2025",
  },
  {
    id: 30,
    tasks: "Annabell",
    status: null,
    notes: "Pellentesque at nulla.",
    due_date: "3/22/2024",
    entry_date: "1/9/2025",
  },
  {
    id: 31,
    tasks: "Ricard",
    status: null,
    notes:
      "Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.",
    due_date: "9/2/2024",
    entry_date: "5/11/2024",
  },
  {
    id: 32,
    tasks: "Staffard",
    status: null,
    notes:
      "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.",
    due_date: "1/5/2025",
    entry_date: "1/26/2025",
  },
  {
    id: 33,
    tasks: "Esra",
    status: null,
    notes: "In eleifend quam a odio.",
    due_date: "7/18/2024",
    entry_date: "12/27/2024",
  },
  {
    id: 34,
    tasks: "Chester",
    status: null,
    notes: "Etiam faucibus cursus urna. Ut tellus.",
    due_date: "2/13/2025",
    entry_date: "1/11/2025",
  },
  {
    id: 35,
    tasks: "Godfry",
    status: null,
    notes: "Nullam sit amet turpis elementum ligula vehicula consequat.",
    due_date: "2/7/2025",
    entry_date: "9/22/2024",
  },
  {
    id: 36,
    tasks: "Helenelizabeth",
    status: null,
    notes:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.",
    due_date: "2/14/2025",
    entry_date: "10/21/2024",
  },
  {
    id: 37,
    tasks: "Siffre",
    status: null,
    notes:
      "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.",
    due_date: "2/19/2025",
    entry_date: "5/15/2024",
  },
  {
    id: 38,
    tasks: "Jeanette",
    status: null,
    notes:
      "Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    due_date: "9/23/2024",
    entry_date: "8/5/2024",
  },
  {
    id: 39,
    tasks: "Amandie",
    status: null,
    notes: "Pellentesque ultrices mattis odio. Donec vitae nisi.",
    due_date: "8/20/2024",
    entry_date: "1/17/2025",
  },
  {
    id: 40,
    tasks: "Bertrando",
    status: null,
    notes: "Suspendisse accumsan tortor quis turpis. Sed ante.",
    due_date: "7/16/2024",
    entry_date: "1/25/2025",
  },
  {
    id: 41,
    tasks: "Kikelia",
    status: null,
    notes:
      "Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.",
    due_date: "6/21/2024",
    entry_date: "9/7/2024",
  },
  {
    id: 42,
    tasks: "Ursuline",
    status: null,
    notes: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    due_date: "5/21/2024",
    entry_date: "1/2/2025",
  },
  {
    id: 43,
    tasks: "Ferd",
    status: null,
    notes: "Morbi ut odio.",
    due_date: "1/1/2025",
    entry_date: "6/10/2024",
  },
  {
    id: 44,
    tasks: "Adrianne",
    status: null,
    notes:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.",
    due_date: "11/10/2024",
    entry_date: "3/29/2024",
  },
  {
    id: 45,
    tasks: "Aeriel",
    status: null,
    notes: "Nulla nisl.",
    due_date: "1/1/2025",
    entry_date: "10/31/2024",
  },
  {
    id: 46,
    tasks: "Dewie",
    status: null,
    notes: "Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
    due_date: "3/31/2024",
    entry_date: "12/8/2024",
  },
  {
    id: 47,
    tasks: "Devin",
    status: null,
    notes: "Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    due_date: "10/12/2024",
    entry_date: "6/18/2024",
  },
  {
    id: 48,
    tasks: "Whitman",
    status: null,
    notes:
      "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.",
    due_date: "4/4/2024",
    entry_date: "12/25/2024",
  },
  {
    id: 49,
    tasks: "Tedd",
    status: null,
    notes: "Donec dapibus. Duis at velit eu est congue elementum.",
    due_date: "12/27/2024",
    entry_date: "1/14/2025",
  },
  {
    id: 50,
    tasks: "Gardener",
    status: null,
    notes:
      "In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    due_date: "10/14/2024",
    entry_date: "11/15/2024",
  },
  {
    id: 51,
    tasks: "Nicolais",
    status: null,
    notes: "Proin interdum mauris non ligula pellentesque ultrices.",
    due_date: "10/2/2024",
    entry_date: "2/5/2025",
  },
  {
    id: 52,
    tasks: "Sigfried",
    status: null,
    notes: "Duis ac nibh.",
    due_date: "7/25/2024",
    entry_date: "2/14/2025",
  },
  {
    id: 53,
    tasks: "Gearalt",
    status: null,
    notes:
      "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.",
    due_date: "11/21/2024",
    entry_date: "5/5/2024",
  },
  {
    id: 54,
    tasks: "Kennedy",
    status: null,
    notes:
      "Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.",
    due_date: "4/7/2024",
    entry_date: "3/28/2024",
  },
  {
    id: 55,
    tasks: "Matt",
    status: null,
    notes: "Nullam molestie nibh in lectus.",
    due_date: "12/9/2024",
    entry_date: "2/2/2025",
  },
  {
    id: 56,
    tasks: "Gauthier",
    status: null,
    notes: "Nulla suscipit ligula in lacus.",
    due_date: "11/29/2024",
    entry_date: "4/5/2024",
  },
  {
    id: 57,
    tasks: "Emory",
    status: null,
    notes: "Morbi non lectus.",
    due_date: "2/16/2025",
    entry_date: "7/9/2024",
  },
  {
    id: 58,
    tasks: "Georgetta",
    status: null,
    notes: "Pellentesque ultrices mattis odio. Donec vitae nisi.",
    due_date: "11/4/2024",
    entry_date: "5/30/2024",
  },
  {
    id: 59,
    tasks: "Rebbecca",
    status: null,
    notes: "Morbi a ipsum.",
    due_date: "6/29/2024",
    entry_date: "8/11/2024",
  },
  {
    id: 60,
    tasks: "Eamon",
    status: null,
    notes:
      "Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.",
    due_date: "9/15/2024",
    entry_date: "3/27/2024",
  },
  {
    id: 61,
    tasks: "Aubrie",
    status: null,
    notes: "Integer ac neque. Duis bibendum.",
    due_date: "12/15/2024",
    entry_date: "3/26/2024",
  },
  {
    id: 62,
    tasks: "Ephraim",
    status: null,
    notes: "In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    due_date: "2/6/2025",
    entry_date: "9/6/2024",
  },
  {
    id: 63,
    tasks: "Wenonah",
    status: null,
    notes: "Suspendisse ornare consequat lectus.",
    due_date: "11/17/2024",
    entry_date: "1/5/2025",
  },
  {
    id: 64,
    tasks: "Avictor",
    status: null,
    notes: "Fusce posuere felis sed lacus.",
    due_date: "9/5/2024",
    entry_date: "5/12/2024",
  },
  {
    id: 65,
    tasks: "Courtney",
    status: null,
    notes: "Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.",
    due_date: "12/21/2024",
    entry_date: "5/21/2024",
  },
  {
    id: 66,
    tasks: "Jacquetta",
    status: null,
    notes: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    due_date: "8/19/2024",
    entry_date: "10/17/2024",
  },
  {
    id: 67,
    tasks: "Kyle",
    status: null,
    notes:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
    due_date: "6/4/2024",
    entry_date: "12/5/2024",
  },
  {
    id: 68,
    tasks: "Fons",
    status: null,
    notes: "Aenean auctor gravida sem.",
    due_date: "11/19/2024",
    entry_date: "3/12/2024",
  },
  {
    id: 69,
    tasks: "Christabella",
    status: null,
    notes:
      "Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    due_date: "3/2/2024",
    entry_date: "7/30/2024",
  },
  {
    id: 70,
    tasks: "Conny",
    status: null,
    notes: "Nullam molestie nibh in lectus. Pellentesque at nulla.",
    due_date: "6/24/2024",
    entry_date: "7/6/2024",
  },
  {
    id: 71,
    tasks: "Theobald",
    status: null,
    notes:
      "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.",
    due_date: "12/13/2024",
    entry_date: "11/1/2024",
  },
  {
    id: 72,
    tasks: "Agathe",
    status: null,
    notes: "Fusce consequat. Nulla nisl.",
    due_date: "5/15/2024",
    entry_date: "12/8/2024",
  },
  {
    id: 73,
    tasks: "Wanids",
    status: null,
    notes:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
    due_date: "8/23/2024",
    entry_date: "11/14/2024",
  },
  {
    id: 74,
    tasks: "Boycie",
    status: null,
    notes:
      "Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.",
    due_date: "8/26/2024",
    entry_date: "11/30/2024",
  },
  {
    id: 75,
    tasks: "Robena",
    status: null,
    notes:
      "Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
    due_date: "11/27/2024",
    entry_date: "6/15/2024",
  },
  {
    id: 76,
    tasks: "Gray",
    status: null,
    notes: "Aenean lectus. Pellentesque eget nunc.",
    due_date: "2/4/2025",
    entry_date: "9/20/2024",
  },
  {
    id: 77,
    tasks: "Riva",
    status: null,
    notes:
      "Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    due_date: "7/3/2024",
    entry_date: "12/3/2024",
  },
  {
    id: 78,
    tasks: "Pippa",
    status: null,
    notes: "Morbi quis tortor id nulla ultrices aliquet.",
    due_date: "5/4/2024",
    entry_date: "6/14/2024",
  },
  {
    id: 79,
    tasks: "Jerrold",
    status: null,
    notes: "Aliquam quis turpis eget elit sodales scelerisque.",
    due_date: "6/2/2024",
    entry_date: "3/13/2024",
  },
  {
    id: 80,
    tasks: "Rozanna",
    status: null,
    notes: "Pellentesque at nulla. Suspendisse potenti.",
    due_date: "6/6/2024",
    entry_date: "6/3/2024",
  },
  {
    id: 81,
    tasks: "Gerrie",
    status: null,
    notes: "Morbi a ipsum. Integer a nibh.",
    due_date: "9/28/2024",
    entry_date: "2/3/2025",
  },
  {
    id: 82,
    tasks: "Pam",
    status: null,
    notes: "Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.",
    due_date: "11/24/2024",
    entry_date: "11/21/2024",
  },
  {
    id: 83,
    tasks: "Ivory",
    status: null,
    notes:
      "In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.",
    due_date: "9/27/2024",
    entry_date: "3/5/2024",
  },
  {
    id: 84,
    tasks: "Norean",
    status: null,
    notes:
      "Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.",
    due_date: "5/11/2024",
    entry_date: "11/22/2024",
  },
  {
    id: 85,
    tasks: "Che",
    status: null,
    notes:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.",
    due_date: "3/17/2024",
    entry_date: "1/31/2025",
  },
  {
    id: 86,
    tasks: "Webster",
    status: null,
    notes:
      "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    due_date: "6/24/2024",
    entry_date: "1/8/2025",
  },
  {
    id: 87,
    tasks: "Caterina",
    status: null,
    notes: "Nulla nisl. Nunc nisl.",
    due_date: "11/29/2024",
    entry_date: "4/1/2024",
  },
  {
    id: 88,
    tasks: "Giffy",
    status: null,
    notes: "Aliquam non mauris. Morbi non lectus.",
    due_date: "12/21/2024",
    entry_date: "11/9/2024",
  },
  {
    id: 89,
    tasks: "Hedy",
    status: null,
    notes: "Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.",
    due_date: "2/7/2025",
    entry_date: "10/13/2024",
  },
  {
    id: 90,
    tasks: "Yasmeen",
    status: null,
    notes: "Proin at turpis a pede posuere nonummy.",
    due_date: "5/16/2024",
    entry_date: "5/4/2024",
  },
  {
    id: 91,
    tasks: "Annabelle",
    status: null,
    notes:
      "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.",
    due_date: "12/15/2024",
    entry_date: "6/26/2024",
  },
  {
    id: 92,
    tasks: "Ruddie",
    status: null,
    notes: "Maecenas tincidunt lacus at velit.",
    due_date: "6/27/2024",
    entry_date: "6/7/2024",
  },
  {
    id: 93,
    tasks: "Thor",
    status: null,
    notes: "Phasellus in felis.",
    due_date: "6/6/2024",
    entry_date: "1/20/2025",
  },
  {
    id: 94,
    tasks: "Kyle",
    status: null,
    notes:
      "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.",
    due_date: "6/3/2024",
    entry_date: "11/16/2024",
  },
  {
    id: 95,
    tasks: "Alecia",
    status: null,
    notes:
      "Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.",
    due_date: "10/1/2024",
    entry_date: "10/14/2024",
  },
  {
    id: 96,
    tasks: "Lilah",
    status: null,
    notes: "Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    due_date: "10/4/2024",
    entry_date: "3/16/2024",
  },
  {
    id: 97,
    tasks: "Winonah",
    status: null,
    notes: "Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    due_date: "3/21/2024",
    entry_date: "10/1/2024",
  },
  {
    id: 98,
    tasks: "Celle",
    status: null,
    notes: "Nam dui.",
    due_date: "4/15/2024",
    entry_date: "8/3/2024",
  },
  {
    id: 99,
    tasks: "Merola",
    status: null,
    notes:
      "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.",
    due_date: "3/27/2024",
    entry_date: "9/6/2024",
  },
  {
    id: 100,
    tasks: "Lezley",
    status: null,
    notes:
      "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.",
    due_date: "3/13/2024",
    entry_date: "7/23/2024",
  },
];
